import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from '../components/common/sidebar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className} style={{ display: 'flex', marginLeft:'-80px', marginTop:'80px' }}>
        <Sidebar />
        <div style={{ flexGrow: 1 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
